# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 299d01f128eb773892919434446259051982397fd383812099053f43a5891abcd0403fb60008b09225d3d28e3e610223c8afcba4fa07a56507447501f5fadb43

test:
  secret_key_base: e287584bde3074a9b642b8631c8a5694f6df283696ee5cb16f1ad541bda7378521f16ee061b896690f4366dc6a077026ec82e80ad644543340c8841adb22bc39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
